; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = drupal

; Modules
projects[] = module_filter
projects[] = ctools
projects[] = views
projects[] = entity
projects[] = admin_views
projects[] = views_bulk_operations
projects[] = panels
projects[] = metatag
projects[] = libraries
projects[] = pathauto
projects[] = token
projects[] = transliteration
projects[] = wysiwyg
projects[] = admin_menu

; Themes
projects[] = bootstrap
